FileVersion = 1
Dependencies = {corlib = "*", libpng-beef = "*"}

[Project]
Name = "example"
TargetType = "BeefGUIApplication"
StartupObject = "example.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
