FileVersion = 1

[Project]
Name = "libpng-beef"
DefaultNamespace = "libpng"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\libpng.lib", "$(ProjectDir)\\libs\\zlib.lib"]
PreprocessorMacros = ["DEBUG", "PNG_STDIO_SUPPORTED", "PNG_INFO_IMAGE_SUPPORTED", "PNG_SEQUENTIAL_READ_SUPPORTED", "PNG_WRITE_SUPPORTED", "PNG_EASY_ACCESS_SUPPORTED"]
